- name: update web servers
  hosts: web_dev
  remote_user: root
tasks:
- name: ensure apache is at the latest version
  yum:
  name: httpd
  state: latest
- name: write the apache config file
  template:
  src: /srv/httpd.j2
  dest: /etc/httpd.conf

- name: Install python3-pip 
  apt:
  name: python3-pip
  update_cache: true

- name: Start flask application
  shell: "python3 -m flask run --host=0.0.0.0"
  environment:
    FLASK_APP: /vagrant/app.py

tasks:
- name: Write the apache config file
  ansible.builtin.template:
    src: /srv/httpd.j2
    dest: /etc/httpd.conf
  notify:
  - Restart apache
handlers:
- name: Restart apache
  ansible.builtin.service:
  name: httpd
  state: restarted